### ISSUE TITLE
Question

### ISSUE THREAD

**Issue by KudoAmine** [on-three/akagi#1]
Hi,

Firstly, Thank you for subbing this Drama!

Secondly, I would like to know if you are planning to sub the upcoming season!
For me, I don't understand Japanese.. But I'm willing to help on timing the subs and correcting grammatical errors.

If there is a way to be in contact wit you, please tell me..
Thanks again.

**Comment by on-three** [comment]
Thanks for the kind words KudoAmine.
Honestly I only put these together because no one else did. Only really did it for the IRC channel I hang in, so that's why I put a lot of jokes in the subs.
Still, we have the same plan for the upcoming 3 episode end of the Washizu arc on May 25th. If we don't see subs coming out within a few weeks, I'll def try my best to provide some. If that's the case you'll probably see me start to work on them in this repo in early June. I honestly hope I don't have to as I think there are people who can do it better and faster, but it will get done one way or another.
if you have any corrections at all just provide a Github Pull Request. I'll merge them. We also hang in IRC on rizon. My primary channel is #/tv/shows but I'd warn against going there unless you can handle some shittalking ;-). It's not an exclusively weeb channel, but we do watch Idol music and a lot of Japanese shows on Saturdays.

**Comment by KudoAmine** [comment]
Thank you for your reply.

Good to hear that, I personally lost hope for other people to sub this drama.. Since this season was out for quite a long time and no one subbed it.
Also, You guys did pretty well with the subtitles.. There was only some small mistakes, I'll make sure to do as you said and create a Pull Request with the corrections.

I'll make sure to check your IRC channel too.. I can't be bothered by some shittalking x)
